### ISSUE TITLE
E2EE Contact Lists

### ISSUE THREAD

**Issue by trymeouteh** [xsf/xeps#1078]
Please create a XEP which will encrypt contacts stored on a XMPP server were only the user can access the contacts for good privacy.

**Comment by mwild1** [comment]
Hi, thanks for filing this issue! You filed a bunch of issues overnight. They're all off-topic for this issue tracker, so I'll be closing them with this message and additional comments if relevant. The best place for discussion about current and future XEPs is the XSF standards mailing list. You can find all our mailing lists linked from: https://xmpp.org/community/mailing-lists.html . Looking forward to your contributions :)

---

This is bordering on "not possible", at a protocol level without compromising on some features of XMPP. The server needs to know who the user's contacts are so that it can deny strangers the ability to view the user's status, and implement other similar privacy protections. Encrypting the contact list would also mean the user would lose all their contacts in case of device loss and a forgotten password.

There have been some experiments with Prosody to encrypt the user's contact list while they are offline, which can minimize the impact of a server compromise for offline users or inactive accounts. But that is not a protocol issue, and the XSF and XEPs are about documenting the protocol.
