### ISSUE TITLE
make pdf

### ISSUE THREAD

**Issue by imaginator** [xsf/xeps#121]
`make PDF` is failing

``` 
simon@crater  /tmp/xeps   master  make pdf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19415    0 19415    0     0  20016      0 --:--:-- --:--:-- --:--:-- 20015
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 88726  100 88726    0     0  78655      0  0:00:01  0:00:01 --:--:-- 78727
This is XeTeX, Version 3.1415926-2.5-0.9999.3 (TeX Live 2013/Debian)
 restricted \write18 enabled.
entering extended mode
! I can't find file `build/xepbuild/xep-0001.xml.texml.tex'.
<*> build/xepbuild/xep-0001.xml.texml.tex

(Press Enter to retry, or Control-D to exit)
Please type another input file name:
```

I've checked the "missing" file and `build/xepbuild/xep-0001.xml.texml.tex` is in the directory.

**Comment by winfried** [comment]
The PFD generation in the Makefile looks quite broken to me. It tries to process the texml.tex file just before texml is invoked to generate the texml.tex file. Also, when a XEP has inline images, it doesn't include those images.

I think it would be better to leave building the PDF to the xsf-tools and not try to build them in the makefile.

**Comment by SamWhited** [comment]
> I think it would be better to leave building the PDF to the xsf-tools and not try to build them in the makefile.

Agreed. Please kill it with fire. I feel dirty.

**Comment by winfried** [comment]
Fixed by https://github.com/xsf/xsf-tools/commit/4d42f679f76e341d3eccbfddaca8f0d674529914

Note that build.py takes (at my box at least) appr. 20 minutes to build everything.
build.py also creates:
- xeplist.txt, a snippet of html that can be used for an overview table, like http://xmpp.org/xmpp-protocols/xmpp-extensions/
- xeps.xml, an overview of all xeps in xml
- xepbundle.tar.bz2, everything wrapped up

Also note the commandline argument is --imagespath, not --imagepath
