### ISSUE TITLE
New CSS brings issues with horizontal scrolling on some XEPs

### ISSUE THREAD

**Issue by edhelas** [xsf/xeps#514]
See https://xmpp.org/extensions/xep-0385.html

**Comment by horazont** [comment]
The options I can think of:

1. Adapt the CSS to make the code example boxes wider (e.g. to full width), while keeping the normal text at the current width.
2. Revert the CSS change from #511.
3. Adapt the CSS to add scrollbars to the code examples so that the width of the full document is still restricted.
4. Go over all XEPs and fix their widths. I don’t see that this will be a full fix everywhere.

(We should do (4) nevertheless.)

Thoughts?

**Comment by SamWhited** [comment]
This was already a problem, the new readability changes just make it more apparent. At least for now, would anyone object to just setting `overflow: scroll;` on `pre`?

![overflow example](https://user-images.githubusercontent.com/512573/30702803-8f2490a8-9eb3-11e7-958d-14d01473b3fb.png)

**Comment by horazont** [comment]
+1 for ``overflow: scroll``.
