### ISSUE TITLE
XEP-0060: 'max-nodes-exceeded' is not described anywhere

### ISSUE THREAD

**Issue by sco0ter** [xsf/xeps#581]
The `max-nodes-exceeded` error (`http://jabber.org/protocol/pubsub#errors` namespace) is present in the XML schema, but it lacks any textual description.

Either remove the element from the XML schema or describe when to use the error.

**Comment by horazont** [comment]
Thanks for the report. This repository is not watched by everyone in the standards process, but mostly by editors.

Since this is a technical change (it would need some kind of normative language to fix), please re-post this [on the standards mailing list](https://mail.jabber.org/mailman/listinfo/standards).

Thank you.

P.S.: If you don’t want to, I can handle that for you, but I think it’s better when the original reporter does that.
